"""
segmenter.py — Chapter boundary detection for the YouTube summariser.

Detects topic shifts by computing sliding-window cosine similarity on
``all-MiniLM-L6-v2`` sentence embeddings — the same model already used by
``scorer.py``.  Boundaries are identified where similarity drops sharply;
each resulting chapter receives a short title generated by BART or, when
that is unavailable, by TF-IDF keyword extraction.

Heavy libraries (sentence_transformers, transformers, sklearn) are imported
lazily so this module stays importable without them installed.
"""

import logging
import warnings
from dataclasses import dataclass
from typing import List

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module-level lazy caches
# ---------------------------------------------------------------------------

_bart_pipeline = None
_bart_warned: bool = False

# ---------------------------------------------------------------------------
# Public dataclass
# ---------------------------------------------------------------------------


@dataclass
class Chapter:
    """A contiguous group of :class:`~enricher.EnrichedSegment` objects."""

    index: int
    start: float  # seconds (start of first segment in chapter)
    end: float  # seconds (end of last segment in chapter)
    title: str  # generated by BART or extracted from dominant terms
    segments: list  # list of EnrichedSegment indices (ints)
    summary: str = ""  # filled in by synthesiser.py later


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def detect_chapters(
    enriched_segments: list,
    min_chapter_duration: float = 60.0,
) -> List[Chapter]:
    """Detect chapter boundaries from a list of enriched segments.

    Uses cosine similarity between sliding windows of sentence embeddings to
    find topic shifts.  Each resulting chapter is assigned a short title via
    :func:`_generate_chapter_title`.

    Parameters
    ----------
    enriched_segments:
        List of :class:`~enricher.EnrichedSegment` objects (or any objects
        that expose ``.full_text``, ``.start``, and ``.end``).
    min_chapter_duration:
        Minimum duration (seconds) a chapter must span before a new boundary
        is accepted.  Prevents overly granular splitting.

    Returns
    -------
    list[Chapter]
        Chapters in chronological order.  Returns a single chapter covering
        the entire video when fewer than four segments are provided.
    """
    n = len(enriched_segments)

    if n < 4:
        return _single_chapter(enriched_segments)

    # ------------------------------------------------------------------
    # 1. Encode all segments
    # ------------------------------------------------------------------
    texts = [seg.full_text for seg in enriched_segments]
    embeddings = _encode_texts(texts)

    if embeddings is None:
        # sentence_transformers unavailable — one chapter for everything
        return _single_chapter(enriched_segments)

    # ------------------------------------------------------------------
    # 2. Sliding-window cosine similarity
    # ------------------------------------------------------------------
    topic_shift = _compute_topic_shifts(embeddings)

    # ------------------------------------------------------------------
    # 3. Find boundary indices
    # ------------------------------------------------------------------
    boundaries = _find_boundaries(
        topic_shift,
        enriched_segments,
        min_chapter_duration,
        window_offset=2,  # first valid shift index (window requires i>=2)
    )

    # ------------------------------------------------------------------
    # 4. Build Chapter objects
    # ------------------------------------------------------------------
    chapters = _build_chapters(boundaries, enriched_segments)
    return chapters


# ---------------------------------------------------------------------------
# Private helpers — chapter construction
# ---------------------------------------------------------------------------


def _single_chapter(enriched_segments: list) -> List[Chapter]:
    """Return a list with one Chapter covering all *enriched_segments*."""
    if not enriched_segments:
        return []

    texts = [seg.full_text for seg in enriched_segments]
    title = _generate_chapter_title(texts)
    return [
        Chapter(
            index=0,
            start=enriched_segments[0].start,
            end=enriched_segments[-1].end,
            title=title,
            segments=list(range(len(enriched_segments))),
        )
    ]


def _build_chapters(
    boundary_indices: List[int],
    enriched_segments: list,
) -> List[Chapter]:
    """Slice *enriched_segments* at *boundary_indices* and build Chapter objects.

    *boundary_indices* is a sorted list of segment positions where a new chapter
    starts (the very first chapter always starts at index 0).
    """
    starts = sorted(set([0] + boundary_indices))
    # Sentinel: one past the last segment
    starts.append(len(enriched_segments))

    chapters: List[Chapter] = []
    for chapter_idx, (seg_start, seg_end) in enumerate(zip(starts[:-1], starts[1:])):
        chapter_segs = enriched_segments[seg_start:seg_end]
        if not chapter_segs:
            continue

        texts = [seg.full_text for seg in chapter_segs]
        title = _generate_chapter_title(texts)

        chapters.append(
            Chapter(
                index=chapter_idx,
                start=chapter_segs[0].start,
                end=chapter_segs[-1].end,
                title=title,
                segments=list(range(seg_start, seg_end)),
            )
        )

    return chapters


# ---------------------------------------------------------------------------
# Private helpers — similarity / boundary detection
# ---------------------------------------------------------------------------


def _encode_texts(texts: List[str]):
    """Encode *texts* with ``all-MiniLM-L6-v2`` and return an ndarray or None."""
    try:
        from sentence_transformers import SentenceTransformer  # noqa: PLC0415
    except ImportError:
        warnings.warn(
            "sentence-transformers is not installed; chapter detection will produce "
            "a single chapter.  Install with: pip install sentence-transformers",
            ImportWarning,
            stacklevel=3,
        )
        return None

    try:
        model = SentenceTransformer("all-MiniLM-L6-v2")
        return model.encode(texts, batch_size=32, show_progress_bar=False)
    except Exception as exc:
        logger.warning("Embedding failed: %s", exc)
        return None


def _cosine_similarity(a, b) -> float:
    """Compute cosine similarity between two 1-D numpy arrays."""
    import numpy as np  # noqa: PLC0415

    denom = np.linalg.norm(a) * np.linalg.norm(b)
    if denom == 0.0:
        return 0.0
    return float(np.dot(a, b) / denom)


def _compute_topic_shifts(embeddings) -> List[float]:
    """Return a topic-shift score for each valid window position.

    The window comparison at position *i* contrasts the mean of
    ``embeddings[i-2 : i+1]`` against ``embeddings[i+1 : i+4]``.

    Valid range: i in [2, len-3) → produces ``len - 5`` values.
    """
    import numpy as np  # noqa: PLC0415

    n = len(embeddings)
    topic_shift: List[float] = []

    for i in range(2, n - 3):
        left_mean = np.mean(embeddings[i - 2 : i + 1], axis=0)
        right_mean = np.mean(embeddings[i + 1 : i + 4], axis=0)
        sim = _cosine_similarity(left_mean, right_mean)
        topic_shift.append(1.0 - sim)

    return topic_shift


def _find_boundaries(
    topic_shift: List[float],
    enriched_segments: list,
    min_chapter_duration: float,
    window_offset: int,
) -> List[int]:
    """Find segment indices where new chapters should begin.

    A segment at shifted index *k* is a boundary candidate when:

    * ``topic_shift[k] > mean + 0.5 * std``
    * The gap from the previous accepted boundary is >= *min_chapter_duration*.

    Parameters
    ----------
    topic_shift:
        Pre-computed shift scores (length = n - 5 for window_offset=2).
    enriched_segments:
        Full list of segments (for timestamp look-up).
    min_chapter_duration:
        Minimum seconds between accepted boundaries.
    window_offset:
        Index into *enriched_segments* that corresponds to ``topic_shift[0]``.

    Returns
    -------
    list[int]
        Sorted list of segment indices (into *enriched_segments*) that start a
        new chapter.  Does NOT include index 0 (the implicit first chapter start).
    """
    if not topic_shift:
        return []

    import numpy as np  # noqa: PLC0415

    arr = np.array(topic_shift)
    threshold = arr.mean() + 0.5 * arr.std()

    boundaries: List[int] = []
    prev_boundary_start = enriched_segments[0].start

    for k, shift in enumerate(topic_shift):
        seg_idx = k + window_offset
        if seg_idx >= len(enriched_segments):
            break

        if shift <= threshold:
            continue

        seg_start = enriched_segments[seg_idx].start
        if seg_start - prev_boundary_start >= min_chapter_duration:
            boundaries.append(seg_idx)
            prev_boundary_start = seg_start

    return boundaries


# ---------------------------------------------------------------------------
# Private helpers — chapter titling
# ---------------------------------------------------------------------------


def _generate_chapter_title(texts: List[str]) -> str:
    """Generate a short descriptive title for a chapter.

    Attempts BART summarisation (``facebook/bart-large-cnn``) with
    ``max_length=10``.  Falls back to :func:`_tfidf_title_fallback` when
    transformers is unavailable, the combined text is too short for
    summarisation, or the model call fails.

    Never raises — always returns a non-empty string.
    """
    global _bart_pipeline, _bart_warned

    combined = " ".join(texts)[:512].strip()

    if not combined:
        return _tfidf_title_fallback(texts)

    # Only attempt BART when we have enough material
    if len(combined.split()) < 10:
        return _tfidf_title_fallback(texts)

    try:
        from transformers import pipeline as hf_pipeline  # noqa: PLC0415
    except ImportError:
        if not _bart_warned:
            warnings.warn(
                "transformers is not installed; chapter titles will use TF-IDF "
                "keyword extraction.  Install with: pip install transformers",
                ImportWarning,
                stacklevel=2,
            )
            _bart_warned = True
        return _tfidf_title_fallback(texts)

    try:
        if _bart_pipeline is None:
            _bart_pipeline = hf_pipeline(
                "text2text-generation",
                model="facebook/bart-large-cnn",
            )

        result = _bart_pipeline(
            combined,
            max_length=10,
            min_length=3,
            do_sample=False,
        )
        title = result[0]["summary_text"].strip()
        return title if title else _tfidf_title_fallback(texts)

    except Exception as exc:
        logger.warning("BART title generation failed: %s", exc)
        return _tfidf_title_fallback(texts)


def _tfidf_title_fallback(texts: List[str]) -> str:
    """Return top-4 TF-IDF terms from *texts* joined with ' · '.

    Uses ``sklearn.feature_extraction.text.TfidfVectorizer``.  Returns
    ``"Chapter"`` when the vocabulary is empty or sklearn is unavailable.
    """
    if not texts or not any(t.strip() for t in texts):
        return "Chapter"

    try:
        import numpy as np  # noqa: PLC0415
        from sklearn.feature_extraction.text import TfidfVectorizer  # noqa: PLC0415

        vectorizer = TfidfVectorizer(
            stop_words="english",
            max_features=200,
        )
        matrix = vectorizer.fit_transform(texts)
        # sklearn's sparse matrix type isn't fully resolved by pyright;
        # np.asarray on the csr_matrix gives a 2-D array we can sum safely.
        scores_arr = np.asarray(matrix.sum(axis=0)).flatten()
        terms: List[str] = list(vectorizer.get_feature_names_out())

        top_indices = scores_arr.argsort()[::-1][:4]
        top_terms = [terms[int(i)] for i in top_indices if scores_arr[int(i)] > 0]

        return " · ".join(top_terms) if top_terms else "Chapter"

    except Exception as exc:
        logger.warning("TF-IDF title fallback failed: %s", exc)
        return "Chapter"
